CHANGELOG.md, lib/e2e/transaction.spec.ts, lib/src/core/cro.ts, lib/src/network/network.ts, lib/src/network/ow.types.ts, lib/src/transaction/amino.spec.ts, lib/src/transaction/msg/bank/msgsend.spec.ts, lib/src/transaction/msg/distribution/MsgWithdrawDelegatorReward.spec.ts, lib/src/transaction/msg/distribution/MsgWithdrawValidatorCommission.spec.ts, lib/src/transaction/msg/gov/MsgDeposit.spec.ts, lib/src/transaction/msg/gov/MsgSubmitProposal.spec.ts, lib/src/transaction/msg/gov/MsgVote.spec.ts, lib/src/transaction/msg/staking/MsgBeginRedelegate.spec.ts, lib/src/transaction/msg/staking/MsgCreateValidator.spec.ts, lib/src/transaction/msg/staking/MsgDelegate.spec.ts, lib/src/transaction/msg/staking/MsgEditValidator.spec.ts, lib/src/transaction/msg/staking/MsgUndelegate.spec.ts, lib/src/transaction/tx-custom-props.spec.ts, lib/src/transaction/tx-edgecase.spec.ts, package.json
This will be used directly on here https://github.com/crypto-com/token-migration/pull/53#discussion_r573642723
=> Plan v0.0.9 release - Add default node url property and prepare ChangeLog file

lib/src/transaction/msg/staking/MsgUndelegate.spec.ts, lib/src/transaction/msg/staking/MsgUndelegate.ts
Solution add amino json for MsgUndelegate
=> Problem: missing Undelegate for amino json (fix #146)

CHANGELOG.md, lib/src/core/cro.ts, package-lock.json, package.json
Solution: (Fix #156) Update mainnet network config
=> Problem: Missing Mainnet configuration

lib/src/transaction/msg/staking/MsgBeginRedelegate.spec.ts, lib/src/transaction/msg/staking/MsgBeginRedelegate.ts
Solution: add amino json for MsgBeginRedelegate
=> Problem: missing MsgBeginRedelegate amino json (fix #159)

lib/src/cosmos/v1beta1/codec/generated/codecimpl.d.ts, lib/src/cosmos/v1beta1/codec/generated/codecimpl.js, package-lock.json, package.json
=> Bump-version-protobuf-v0.42.4 #166

lib/src/core/cro.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/gov/ow.types.ts, lib/src/transaction/msg/gov/proposal/CancelSoftwareUpgradeProposal.spec.ts, lib/src/transaction/msg/gov/proposal/CancelSoftwareUpgradeProposal.ts
=> Problem: Feature cancel software upgrade proposal #99

lib/src/cosmos/amino/msg.ts, lib/src/transaction/msg/gov/MsgVote.spec.ts, lib/src/transaction/msg/gov/MsgVote.ts
Solution: add amino json for voting
=> Problem: missing support of proposal amino json (fix #181)

CONTRIBUTION.md
=> Problem: Fix a typo in CONTRIBUTION.md

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/distribution/MsgSetWithdrawAddress.spec.ts, lib/src/transaction/msg/distribution/MsgSetWithdrawAddress.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Feature msg set withdraw address #168

.github/workflows/test_e2e.yml, lib/src/coin/coin.ts, lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/distribution/MsgFundCommunityPool.spec.ts, lib/src/transaction/msg/distribution/MsgFundCommunityPool.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Feature msg fund community pool #168

lib/src/cosmos/v1beta1/codec/generated/codecimpl.d.ts, lib/src/cosmos/v1beta1/codec/generated/codecimpl.js, lib/src/cosmos/v1beta1/scripts/get-proto.sh, lib/src/cosmos/v1beta1/scripts/predefine-proto.sh
=> Problem: NFT-package compiled .proto to typescript files

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/nft/MsgIssueDenom.spec.ts, lib/src/transaction/msg/nft/MsgIssueDenom.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Support MsgIssueDenom for NFT Module

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/nft/MsgMintNFT.spec.ts, lib/src/transaction/msg/nft/MsgMintNFT.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Support MsgMintNFT type on nft module

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/nft/MsgEditNFT.spec.ts, lib/src/transaction/msg/nft/MsgEditNFT.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Support MsgEditNFT type on nft module

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/nft/MsgTransferNFT.spec.ts, lib/src/transaction/msg/nft/MsgTransferNFT.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Support MsgTransferNFT type on nft module

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/nft/MsgBurnNFT.spec.ts, lib/src/transaction/msg/nft/MsgBurnNFT.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Support MsgBurnNFT type on nft module

lib/src/cosmos/v1beta1/codec/generated/codecimpl.d.ts, lib/src/cosmos/v1beta1/codec/generated/codecimpl.js, lib/src/cosmos/v1beta1/scripts/predefine-proto.sh, lib/src/transaction/msg/nft/MsgTransferNFT.spec.ts
=> Problem: Adding IBC compiled types

lib/e2e/transaction.spec.ts, lib/src/transaction/msg/nft/MsgTransferNFT.spec.ts, lib/src/transaction/msg/nft/MsgTransferNFT.ts, lib/src/transaction/msg/ow.types.ts
=> Problem: Bug MsgTransfer NFT remove extra properties

.github/workflows/publish.yaml, README.md, package.json
Solution: (Fix #257) Publish to crypto-org-chain
=> Problem: Not published to crypto-org-chain

lib/src/cosmos/amino/msg.ts, lib/src/transaction/msg/nft/MsgBurnNFT.spec.ts, lib/src/transaction/msg/nft/MsgBurnNFT.ts, lib/src/transaction/msg/nft/MsgEditNFT.spec.ts, lib/src/transaction/msg/nft/MsgEditNFT.ts, lib/src/transaction/msg/nft/MsgIssueDenom.spec.ts, lib/src/transaction/msg/nft/MsgIssueDenom.ts, lib/src/transaction/msg/nft/MsgMintNFT.spec.ts, lib/src/transaction/msg/nft/MsgMintNFT.ts, lib/src/transaction/msg/nft/MsgTransferNFT.spec.ts, lib/src/transaction/msg/nft/MsgTransferNFT.ts, lib/src/transaction/msg/ow.types.ts
Fix #224
Fix #259
Building on top of @calvinaco  PR #260 
This PR contains enhancement on the validation and nft message type.
=> [NFM] Problem: Missing chainmaind CLI level NFT types params validation and amino JSON support

lib/e2e/transaction.spec.ts, lib/src/cosmos/v1beta1/types/tx.ts, lib/src/transaction/raw.spec.ts, lib/src/transaction/raw.ts, lib/src/transaction/signable.ts, lib/src/utils/protoBuf/encoder/authInfo.ts
=> Problem: Support Multiple AuthInfo Fee Amount

lib/src/client/client.spec.ts, lib/src/cosmos/amino/msg.ts, lib/src/transaction/msg/ibc/applications/MsgTransfer.spec.ts, lib/src/transaction/msg/ibc/applications/MsgTransfer.ts, lib/src/transaction/msg/ow.types.ts
- Added IBC Amino support
Fixes #335
=> Problem: add IBC Amino transaction support

lib/src/utils/address.spec.ts, lib/src/utils/address.ts, lib/src/utils/index.ts, package-lock.json, package.json
=> Problem: Support EVM to Bech32 address

lib/src/cosmos/coins.spec.ts, lib/src/cosmos/coins.ts
=> Problem: Support extremely large numbers and removed `uint53`

CHANGELOG.md, package.json
- Added support for transferring very large numbers. Using BigInt
=> Changelog Update v1.0.3

lib/src/core/cro.ts, lib/src/cosmos/v1beta1/codec/generated/codecimpl.d.ts, lib/src/cosmos/v1beta1/codec/generated/codecimpl.js, lib/src/cosmos/v1beta1/scripts/predefine-proto.sh, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/account/DelayedVestingAccount.spec.ts, lib/src/transaction/msg/account/DelayedVestingAccount.ts, lib/src/transaction/msg/account/MsgCreateVestingAccount.spec.ts, lib/src/transaction/msg/account/MsgCreateVestingAccount.ts, lib/src/transaction/msg/ow.types.ts, package-lock.json, package.json
=> Problem: support msg create vesting account

CHANGELOG.md, lib/src/transaction/msg/v2/gov/v2.MsgDeposit.spec.ts, lib/src/transaction/msg/v2/gov/v2.MsgDeposit.ts, package.json
Incorrect proposa_id field as `Long` for Amino format. Should be `string` instead.
=> Problem: Fix MsgDeposit proposa_id field

LICENSE, lib/src/cosmos/v1beta1/adr27.spec.ts, lib/src/cosmos/v1beta1/adr27.ts, lib/src/cosmos/v1beta1/codec/index.ts, lib/src/cosmos/v1beta1/scripts/define-proto.sh, lib/src/cosmos/v1beta1/scripts/get-proto.sh, lib/src/cosmos/v1beta1/scripts/postdefine-proto.sh, lib/src/cosmos/v1beta1/scripts/predefine-proto.sh, lib/src/cosmos/v1beta1/types/typeurls.ts, lib/src/transaction/signable.ts, lib/src/transaction/v2.signable.ts, lib/src/utils/typechecks.spec.ts, lib/src/utils/typechecks.ts
=> Problem: License file is not up-to-dated

CHANGELOG.md, lib/src/core/cro.ts, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/ow.types.ts, lib/src/transaction/msg/slashing/MsgUnjail.spec.ts, lib/src/transaction/msg/slashing/MsgUnjail.ts, lib/src/utils/txDecoder.spec.ts, package-lock.json, package.json
=> #391: MsgUnjail support with unit tests

CHANGELOG.md, lib/src/transaction/common/constants/typeurl.ts, lib/src/transaction/msg/slashing/MsgUnjail.spec.ts, package-lock.json, package.json
Bugfix- add MsgUnjailV2 to the typeurl mapping
=> Bug: Add missing typeurl mapping for MsgUnjailV2
